[workspace]
resolver = "2"
members = [
    "playground",
    "step-sequencer",
    "step-sequencer-tui",
    "step-sequencer-gui/src-tauri",
]
default-members = [
    "step-sequencer",
    "step-sequencer-tui",
    "step-sequencer-gui/src-tauri",
]